name: clam
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.13.3=ha770c72_1
  - gdk-pixbuf=2.42.12=h2b0a6b4_3
  - icu=75.1=he02047a_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h1423503_1
  - lerc=4.0.0=h0aef613_1
  - libdeflate=1.24=h86f0d12_0
  - libdicom=1.2.0=hb03c661_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_4
  - libgcc-ng=15.1.0=h69a702a_4
  - libglib=2.84.3=hf39c6af_0
  - libgomp=15.1.0=h767d61c_4
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libpng=1.6.50=h421ea60_1
  - libsqlite=3.50.4=h0c1763c_0
  - libstdcxx=15.1.0=h8f9b012_4
  - libstdcxx-ng=15.1.0=h4852527_4
  - libtiff=4.7.0=h8261f1e_6
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxml2=2.13.8=h04c0eec_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openjpeg=2.5.3=h55fea9a_1
  - openslide=4.0.0=hacc1dc6_4
  - openslide-python=1.4.2=py310h3616527_1
  - openssl=3.5.2=h26f9b46_0
  - pcre2=10.45=hc749103_0
  - pillow=11.3.0=py310h7e6dc6c_0
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - python=3.10.0=h543edf9_3_cpython
  - python_abi=3.10=8_cp310
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - sqlite=3.50.4=hbc0de68_0
  - tk=8.6.13=noxft_hd72426e_102
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.3.1
      - accelerate==1.10.1
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - asttokens==3.0.0
      - autograd==1.8.0
      - autograd-gamma==0.5.0
      - black==21.4b2
      - blessed==1.23.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - click==8.2.1
      - cloudpickle==3.1.1
      - cmapy==0.6.6
      - comm==0.2.3
      - conch==0.1.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - dcurves==1.1.5
      - debugpy==1.8.16
      - decorator==5.2.1
      - detectron2==0.6
      - einops==0.8.1
      - et-xmlfile==2.0.0
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - filelock==3.13.1
      - fonttools==4.59.1
      - formulaic==1.2.1
      - fsspec==2024.6.1
      - ftfy==6.3.1
      - future==1.0.0
      - fvcore==0.1.5.post20221221
      - gpustat==1.1.1
      - grpcio==1.74.0
      - h5py==3.14.0
      - hf-xet==1.1.8
      - huggingface-hub==0.34.4
      - hydra-core==1.3.2
      - idna==3.10
      - imageio==2.37.0
      - interface-meta==1.3.0
      - iopath==0.1.9
      - ipykernel==6.30.1
      - ipython==8.37.0
      - jedi==0.19.2
      - jinja2==3.1.4
      - joblib==1.5.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - kiwisolver==1.4.9
      - lifelines==0.30.0
      - markdown==3.9
      - markupsafe==2.1.5
      - matplotlib==3.10.5
      - matplotlib-inline==0.1.7
      - mpmath==1.3.0
      - mypy-extensions==1.1.0
      - narwhals==2.5.0
      - nest-asyncio==1.6.0
      - networkx==3.3
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - nystrom-attention==0.0.14
      - omegaconf==2.3.0
      - open-clip-torch==3.1.0
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - openpyxl==3.1.5
      - packaging==25.0
      - pandas==2.3.2
      - parso==0.8.5
      - pathspec==0.12.1
      - patsy==1.0.1
      - pexpect==4.9.0
      - platformdirs==4.4.0
      - portalocker==3.2.0
      - prompt-toolkit==3.0.51
      - protobuf==6.32.0
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycocotools==2.0.10
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydot==4.0.1
      - pygments==2.19.2
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==27.0.2
      - regex==2025.7.34
      - requests==2.32.5
      - safetensors==0.6.2
      - scikit-learn==1.7.1
      - scipy==1.15.3
      - seaborn==0.13.2
      - simsimd==6.5.3
      - six==1.17.0
      - stack-data==0.6.3
      - statsmodels==0.14.5
      - stringzilla==4.0.7
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - timm==1.0.19
      - tokenizers==0.21.4
      - toml==0.10.2
      - topk==1.0
      - torch==2.6.0+cu126
      - torchaudio==2.6.0+cu126
      - torchvision==0.21.0+cu126
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.56.0.dev0
      - triton==3.2.0
      - typing==3.7.4.3
      - typing-extensions==4.12.2
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - wrapt==1.17.3
      - yacs==0.1.8
prefix: /home/clh/anaconda3/envs/clam
